In [2]:
import numpy as np

In [2]:
#apple production data

In [3]:
kanto=np.array([73, 67, 43])

In [9]:
weight= np.array([0.3, 0.2, 0.5])

In [13]:
np.dot(kanto,weight)

np.float64(56.8)

In [14]:
c=np.array([[3,4,5],[2,4,3]])
d=np.array([[2,5,3],[4,3,2]])
print(np.concatenate([c,d],axis=1))

[[3 4 5 2 5 3]
 [2 4 3 4 3 2]]


In [15]:
#CLIMATE DATA

In [5]:
climate_data= np.array([[73, 67, 43],
                        [91, 88 , 64],
                        [87, 134, 58],
                        [102,43, 37],
                        [69, 96, 70]])

In [6]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [10]:
np.matmul(climate_data, weight)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [19]:
climate_data @ weight

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [11]:
data= np.array(climate_data @ weight)

In [12]:
data

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [15]:
final_data=data.reshape(5,1)

In [16]:
final_data

array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [19]:
climate_results=np.concatenate((climate_data,final_data), axis=1)

In [20]:
climate_results

array([[ 73. ,  67. ,  43. ,  56.8],
       [ 91. ,  88. ,  64. ,  76.9],
       [ 87. , 134. ,  58. ,  81.9],
       [102. ,  43. ,  37. ,  57.7],
       [ 69. ,  96. ,  70. ,  74.9]])

In [25]:
np.savetxt('climate_results.txt',
           climate_results,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples',
           comments='')
